-- Заполнение таблицы CLIENT
INSERT INTO CLIENT (LOGIN, PASSWORD) VALUES ('funnyCat', 'meow123');
INSERT INTO CLIENT (LOGIN, PASSWORD) VALUES ('sillyDog', 'bark456');
INSERT INTO CLIENT (LOGIN, PASSWORD) VALUES ('happyPenguin', 'slide789');
INSERT INTO CLIENT (LOGIN, PASSWORD) VALUES ('quirkyOstrich', 'runFast!');
INSERT INTO CLIENT (LOGIN, PASSWORD) VALUES ('cheerfulLlama', 'spitItOut!');
INSERT INTO CLIENT (LOGIN, PASSWORD) VALUES ('wittySquirrel', 'nutsAndBolts');
INSERT INTO CLIENT (LOGIN, PASSWORD) VALUES ('jollyGiraffe', 'tallTales!');
INSERT INTO CLIENT (LOGIN, PASSWORD) VALUES ('merryHippo', 'waterDance!');
INSERT INTO CLIENT (LOGIN, PASSWORD) VALUES ('playfulOtter', 'swimTime!');
INSERT INTO CLIENT (LOGIN, PASSWORD) VALUES ('zanyZebra', 'stripeIt!');

-- Заполнение таблицы CLIENT_INFO 
INSERT INTO CLIENT_INFO (CLIENT_ID, FIRST_NAME, LAST_NAME, MIDDLE_NAME, ADDRESS, EMAIL, PHONE_NUMBER) VALUES (1, 'Bobby', 'Funster', 'W.', '123 Happy St', 'bobbyfun@example.com', '1234567890');
INSERT INTO CLIENT_INFO (CLIENT_ID, FIRST_NAME, LAST_NAME, MIDDLE_NAME, ADDRESS, EMAIL, PHONE_NUMBER) VALUES (2, 'Daisy', 'Wag', 'F.', '456 Silly Ave', 'daisywag@example.com', '2345678901');
INSERT INTO CLIENT_INFO (CLIENT_ID, FIRST_NAME, LAST_NAME, MIDDLE_NAME, ADDRESS, EMAIL, PHONE_NUMBER) VALUES (3, 'Penny', 'Slide', 'G.', '789 Chill Blvd', 'pennyslide@example.com', '3456789012');
INSERT INTO CLIENT_INFO (CLIENT_ID, FIRST_NAME, LAST_NAME, MIDDLE_NAME, ADDRESS, EMAIL, PHONE_NUMBER) VALUES (4, 'Ollie', 'Run', 'H.', '321 Speedy Ln', 'ollierun@example.com', '4567890123');
INSERT INTO CLIENT_INFO (CLIENT_ID, FIRST_NAME, LAST_NAME, MIDDLE_NAME, ADDRESS, EMAIL, PHONE_NUMBER) VALUES (5, 'Lenny', 'Spit', 'I.', '654 Spit St', 'lennyspit@example.com', '5678901234');
INSERT INTO CLIENT_INFO (CLIENT_ID, FIRST_NAME, LAST_NAME, MIDDLE_NAME, ADDRESS, EMAIL, PHONE_NUMBER) VALUES (6, 'Nina', 'Nutty', 'J.', '987 Nut St', 'ninanuts@example.com', '6789012345');
INSERT INTO CLIENT_INFO (CLIENT_ID, FIRST_NAME, LAST_NAME, MIDDLE_NAME, ADDRESS, EMAIL, PHONE_NUMBER) VALUES (7, 'Gary', 'Tall', 'K.', '135 Tall Rd', 'garytall@example.com', '7890123456');
INSERT INTO CLIENT_INFO (CLIENT_ID, FIRST_NAME, LAST_NAME, MIDDLE_NAME, ADDRESS, EMAIL, PHONE_NUMBER) VALUES (8, 'Marty', 'Water', 'L.', '246 Splash St', 'martywater@example.com', '8901234567');
INSERT INTO CLIENT_INFO (CLIENT_ID, FIRST_NAME, LAST_NAME, MIDDLE_NAME, ADDRESS, EMAIL, PHONE_NUMBER) VALUES (9, 'Otto', 'Swim', 'M.', '357 Swim Ln', 'ottoswim@example.com', '9012345678');
INSERT INTO CLIENT_INFO (CLIENT_ID, FIRST_NAME, LAST_NAME, MIDDLE_NAME, ADDRESS, EMAIL, PHONE_NUMBER) VALUES (10, 'Zara', 'Stripe', 'N.', '468 Stripe St', 'zarastripe@example.com', '0123456789');

-- Заполнение таблицы DRIVER
INSERT INTO DRIVER (LOGIN, PASSWORD) VALUES ('speedyTurtle', 'slowAndSteady');
INSERT INTO DRIVER (LOGIN, PASSWORD) VALUES ('ninjaFrog', 'jumpHigh!');
INSERT INTO DRIVER (LOGIN, PASSWORD) VALUES ('crazyKoala', 'sleepyTime!');
INSERT INTO DRIVER (LOGIN, PASSWORD) VALUES ('sneakyFox', 'cleverMoves!');
INSERT INTO DRIVER (LOGIN, PASSWORD) VALUES ('jumpyKangaroo', 'bounceBounce!');
INSERT INTO DRIVER (LOGIN, PASSWORD) VALUES ('charmingParrot', 'talkative!');
INSERT INTO DRIVER (LOGIN, PASSWORD) VALUES ('joyfulPanda', 'bambooLove!');
INSERT INTO DRIVER (LOGIN, PASSWORD) VALUES ('quirkyRaccoon', 'trashDancer!');
INSERT INTO DRIVER (LOGIN, PASSWORD) VALUES ('spunkyFerret', 'playfulSpirit!');
INSERT INTO DRIVER (LOGIN, PASSWORD) VALUES ('dapperPenguin', 'tuxedoTime!');

-- Заполнение таблицы DRIVER_INFO 
INSERT INTO DRIVER_INFO (DRIVER_ID, FIRST_NAME, LAST_NAME, MIDDLE_NAME, ADDRESS, BIRTH_DATE, EMAIL, PASSPORT_NUM, PHONE_NUMBER, VEHICLE_INFO) VALUES (1, 'Terry', 'Shell', 'A.', '111 Turtle Way', CAST('1980-01-01' AS DATE), 'terryshell@example.com', '123456789', '1234567890', 5);
INSERT INTO DRIVER_INFO (DRIVER_ID, FIRST_NAME, LAST_NAME, MIDDLE_NAME, ADDRESS, BIRTH_DATE, EMAIL, PASSPORT_NUM, PHONE_NUMBER, VEHICLE_INFO) VALUES (2, 'Freddy', 'Jump', 'B.', '222 Frog St', CAST('1985-02-02' AS DATE), 'freddyjump@example.com', '234567890', '2345678901', 6);
INSERT INTO DRIVER_INFO (DRIVER_ID, FIRST_NAME, LAST_NAME, MIDDLE_NAME, ADDRESS, BIRTH_DATE, EMAIL, PASSPORT_NUM, PHONE_NUMBER, VEHICLE_INFO) VALUES (3, 'Kylie', 'Koala', 'C.', '333 Sleepy Ln', CAST('1990-03-03' AS DATE), 'kyliek@example.com', '345678901', '3456789012', 7);
INSERT INTO DRIVER_INFO (DRIVER_ID, FIRST_NAME, LAST_NAME, MIDDLE_NAME, ADDRESS, BIRTH_DATE, EMAIL, PASSPORT_NUM, PHONE_NUMBER, VEHICLE_INFO) VALUES (4, 'Fiona', 'Fox', 'D.', '444 Clever Rd', CAST('1995-04-04' AS DATE), 'fionafox@example.com', '456789012', '4567890123', 8);
INSERT INTO DRIVER_INFO (DRIVER_ID, FIRST_NAME, LAST_NAME, MIDDLE_NAME, ADDRESS, BIRTH_DATE, EMAIL, PASSPORT_NUM, PHONE_NUMBER, VEHICLE_INFO) VALUES (5, 'Kylie', 'Kangaroo', 'E.', '555 Bounce Blvd', CAST('1982-05-05' AS DATE), 'kyliekangaroo@example.com', '567890123', '5678901234', 9);
INSERT INTO DRIVER_INFO (DRIVER_ID, FIRST_NAME, LAST_NAME, MIDDLE_NAME, ADDRESS, BIRTH_DATE, EMAIL, PASSPORT_NUM, PHONE_NUMBER, VEHICLE_INFO) VALUES (6, 'Polly', 'Parrot', 'F.', '666 Talk St', CAST('1988-06-06' AS DATE), 'pollyparrot@example.com', '678901234', '6789012345', 10);
INSERT INTO DRIVER_INFO (DRIVER_ID, FIRST_NAME, LAST_NAME, MIDDLE_NAME, ADDRESS, BIRTH_DATE, EMAIL, PASSPORT_NUM, PHONE_NUMBER, VEHICLE_INFO) VALUES (7, 'Penny', 'Panda', 'G.', '777 Bamboo Rd', CAST('1975-07-07' AS DATE), 'pennypanda@example.com', '789012345', '7890123456', 1);
INSERT INTO DRIVER_INFO (DRIVER_ID, FIRST_NAME, LAST_NAME, MIDDLE_NAME, ADDRESS, BIRTH_DATE, EMAIL, PASSPORT_NUM, PHONE_NUMBER, VEHICLE_INFO) VALUES (8, 'Ricky', 'Raccoon', 'H.', '888 Trash Ln', CAST('1993-08-08' AS DATE), 'rickyraccoon@example.com', '890123456', '8901234567', 2);
INSERT INTO DRIVER_INFO (DRIVER_ID, FIRST_NAME, LAST_NAME, MIDDLE_NAME, ADDRESS, BIRTH_DATE, EMAIL, PASSPORT_NUM, PHONE_NUMBER, VEHICLE_INFO) VALUES (9, 'Felix', 'Ferret', 'I.', '999 Fun Blvd', CAST('1987-09-09' AS DATE), 'felixferret@example.com', '901234567', '9012345678', 3);
INSERT INTO DRIVER_INFO (DRIVER_ID, FIRST_NAME, LAST_NAME, MIDDLE_NAME, ADDRESS, BIRTH_DATE, EMAIL, PASSPORT_NUM, PHONE_NUMBER, VEHICLE_INFO) VALUES (10, 'Peter', 'Penguin', 'J.', '1000 Ice St', CAST('1992-10-10' AS DATE), 'peterpenguin@example.com', '012345678', '0123456789', 4);

-- Заполнение таблицы CARGO 
INSERT INTO CARGO (NAME, DESCRIPTION, WEIGHT, VOLUME, CARGO_TYPE, HAZARDOUS) VALUES ('Wacky Widgets', 'Fun and quirky widgets', 100.00, 1.00, 1, 'No');
INSERT INTO CARGO (NAME, DESCRIPTION, WEIGHT, VOLUME, CARGO_TYPE, HAZARDOUS) VALUES ('Silly String', 'Endless fun string', 200.00, 3.00, 2, 'No');
INSERT INTO CARGO (NAME, DESCRIPTION, WEIGHT, VOLUME, CARGO_TYPE, HAZARDOUS) VALUES ('Cheesy Chews', 'Delicious cheese snacks', 50.00, 0.50, 1, 'No');
INSERT INTO CARGO (NAME, DESCRIPTION, WEIGHT, VOLUME, CARGO_TYPE, HAZARDOUS) VALUES ('Bouncy Balls', 'Fun bouncing balls', 150.00, 2.50, 3, 'Class 1');
INSERT INTO CARGO (NAME, DESCRIPTION, WEIGHT, VOLUME, CARGO_TYPE, HAZARDOUS) VALUES ('Magic Potions', 'Mystical potions', 300.00, 4.00, 4, 'Class 2');
INSERT INTO CARGO (NAME, DESCRIPTION, WEIGHT, VOLUME, CARGO_TYPE, HAZARDOUS) VALUES ('Giggle Juice', 'Fun drink', 500.00, 5.00, 5, 'No');
INSERT INTO CARGO (NAME, DESCRIPTION, WEIGHT, VOLUME, CARGO_TYPE, HAZARDOUS) VALUES ('Rainbow Sprinkles', 'Colorful sprinkles', 120.00, 2.00, 2, 'Class 3');
INSERT INTO CARGO (NAME, DESCRIPTION, WEIGHT, VOLUME, CARGO_TYPE, HAZARDOUS) VALUES ('Magic Markers', 'Colorful markers', 30.00, 0.20, 1, 'No');
INSERT INTO CARGO (NAME, DESCRIPTION, WEIGHT, VOLUME, CARGO_TYPE, HAZARDOUS) VALUES ('Jelly Beans', 'Sweet jelly beans', 20.00, 0.10, 1, 'No');
INSERT INTO CARGO (NAME, DESCRIPTION, WEIGHT, VOLUME, CARGO_TYPE, HAZARDOUS) VALUES ('Whimsical Whistles', 'Fun whistles', 250.00, 2.50, 3, 'No');

-- Заполнение таблицы CARGO_TYPE
INSERT INTO CARGO_TYPE (NAME, DESCRIPTION) VALUES ('Fun Stuff', 'General fun items');
INSERT INTO CARGO_TYPE (NAME, DESCRIPTION) VALUES ('Bouncy Goods', 'Items that bounce');
INSERT INTO CARGO_TYPE (NAME, DESCRIPTION) VALUES ('Yummy Treats', 'Food items');
INSERT INTO CARGO_TYPE (NAME, DESCRIPTION) VALUES ('Magic Items', 'Mystical and magical');
INSERT INTO CARGO_TYPE (NAME, DESCRIPTION) VALUES ('Heavy Fun', 'Heavy items for fun');
INSERT INTO CARGO_TYPE (NAME, DESCRIPTION) VALUES ('Colorful Goods', 'Vibrant and colorful');
INSERT INTO CARGO_TYPE (NAME, DESCRIPTION) VALUES ('Art Supplies', 'For creative fun');
INSERT INTO CARGO_TYPE (NAME, DESCRIPTION) VALUES ('Party Goods', 'Items for celebrations');
INSERT INTO CARGO_TYPE (NAME, DESCRIPTION) VALUES ('Novelty Items', 'Unique and quirky');
INSERT INTO CARGO_TYPE (NAME, DESCRIPTION) VALUES ('Sweet Treats', 'Delicious goodies');

-- Заполнение таблицы ORDERS 
INSERT INTO ORDERS (CLIENT_ID, DRIVER_ID, SERVICE_ID, STATUS, ROUTE, DELIVERY_TYPE, TOTAL_WEIGHT, TOTAL_VOLUME, DELIVERED_AT) VALUES (1, 1, 1, 'Pending', 1, 'Fun Express', 100.00, 1.00, NULL);
INSERT INTO ORDERS (CLIENT_ID, DRIVER_ID, SERVICE_ID, STATUS, ROUTE, DELIVERY_TYPE, TOTAL_WEIGHT, TOTAL_VOLUME, DELIVERED_AT) VALUES (2, 2, 2, 'In Transit', 2, 'Party Express', 200.00, 3.00, NULL);
INSERT INTO ORDERS (CLIENT_ID, DRIVER_ID, SERVICE_ID, STATUS, ROUTE, DELIVERY_TYPE, TOTAL_WEIGHT, TOTAL_VOLUME, DELIVERED_AT) VALUES (3, 3, 3, 'Delivered', 3, 'Happy Delivery', 150.00, 2.50, SYSTIMESTAMP);
INSERT INTO ORDERS (CLIENT_ID, DRIVER_ID, SERVICE_ID, STATUS, ROUTE, DELIVERY_TYPE, TOTAL_WEIGHT, TOTAL_VOLUME, DELIVERED_AT) VALUES (4, 4, 4, 'Cancelled', 4, 'Silly Shipping', 300.00, 4.00, NULL);
INSERT INTO ORDERS (CLIENT_ID, DRIVER_ID, SERVICE_ID, STATUS, ROUTE, DELIVERY_TYPE, TOTAL_WEIGHT, TOTAL_VOLUME, DELIVERED_AT) VALUES (5, 5, 5, 'On Hold', 5, 'Joyful Delivery', 500.00, 5.00, NULL);
INSERT INTO ORDERS (CLIENT_ID, DRIVER_ID, SERVICE_ID, STATUS, ROUTE, DELIVERY_TYPE, TOTAL_WEIGHT, TOTAL_VOLUME, DELIVERED_AT) VALUES (6, 6, 6, 'Completed', 6, 'Cheerful Delivery', 100.00, 1.00, SYSTIMESTAMP);
INSERT INTO ORDERS (CLIENT_ID, DRIVER_ID, SERVICE_ID, STATUS, ROUTE, DELIVERY_TYPE, TOTAL_WEIGHT, TOTAL_VOLUME, DELIVERED_AT) VALUES (7, 7, 7, 'Returned', 7, 'Happy Returns', 200.00, 3.00, NULL);
INSERT INTO ORDERS (CLIENT_ID, DRIVER_ID, SERVICE_ID, STATUS, ROUTE, DELIVERY_TYPE, TOTAL_WEIGHT, TOTAL_VOLUME, DELIVERED_AT) VALUES (8, 8, 8, 'Lost', 8, 'Express Delivery', 150.00, 2.50, NULL);
INSERT INTO ORDERS (CLIENT_ID, DRIVER_ID, SERVICE_ID, STATUS, ROUTE, DELIVERY_TYPE, TOTAL_WEIGHT, TOTAL_VOLUME, DELIVERED_AT) VALUES (9, 9, 9, 'Awaiting Pickup', 9, 'Joyful Pickup', 300.00, 4.00, NULL);
INSERT INTO ORDERS (CLIENT_ID, DRIVER_ID, SERVICE_ID, STATUS, ROUTE, DELIVERY_TYPE, TOTAL_WEIGHT, TOTAL_VOLUME, DELIVERED_AT) VALUES (10, 10, 10, 'Exception', 10, 'Silly Shipping', 500.00, 5.00, NULL);

--Заполнение таблицы VEHICLE
INSERT INTO VEHICLE (DRIVER_ID, VEHICLE_TYPE, LICENSE_PLATE, MODEL, CAPACITY, INSURANCE_EXPIRY, STATUS) VALUES (1, 1, 'FUN123', 'Party Bus', 1000.00, CAST('2025-12-31' AS DATE), 'Available');
INSERT INTO VEHICLE (DRIVER_ID, VEHICLE_TYPE, LICENSE_PLATE, MODEL, CAPACITY, INSURANCE_EXPIRY, STATUS) VALUES (2, 2, 'HAPPY456', 'Joy Ride', 1500.00, CAST('2025-12-31' AS DATE), 'In transit');
INSERT INTO VEHICLE (DRIVER_ID, VEHICLE_TYPE, LICENSE_PLATE, MODEL, CAPACITY, INSURANCE_EXPIRY, STATUS) VALUES (3, 1, 'SILLY789', 'Giggle Mobile', 2000.00, CAST('2025-12-31' AS DATE), 'Available');
INSERT INTO VEHICLE (DRIVER_ID, VEHICLE_TYPE, LICENSE_PLATE, MODEL, CAPACITY, INSURANCE_EXPIRY, STATUS) VALUES (4, 2, 'LAUGH012', 'Fun Wagon', 1200.00, CAST('2025-12-31' AS DATE), 'On route');
INSERT INTO VEHICLE (DRIVER_ID, VEHICLE_TYPE, LICENSE_PLATE, MODEL, CAPACITY, INSURANCE_EXPIRY, STATUS) VALUES (5, 1, 'GIGGLE345', 'Jolly Ride', 1600.00, CAST('2025-12-31' AS DATE), 'Available');
INSERT INTO VEHICLE (DRIVER_ID, VEHICLE_TYPE, LICENSE_PLATE, MODEL, CAPACITY, INSURANCE_EXPIRY, STATUS) VALUES (6, 2, 'CHEER678', 'Bouncy Car', 1400.00, CAST('2025-12-31' AS DATE), 'Delayed');
INSERT INTO VEHICLE (DRIVER_ID, VEHICLE_TYPE, LICENSE_PLATE, MODEL, CAPACITY, INSURANCE_EXPIRY, STATUS) VALUES (7, 1, 'SMILE901', 'Happy Van', 1900.00, CAST('2025-12-31' AS DATE), 'Available');
INSERT INTO VEHICLE (DRIVER_ID, VEHICLE_TYPE, LICENSE_PLATE, MODEL, CAPACITY, INSURANCE_EXPIRY, STATUS) VALUES (8, 2, 'FUNNY234', 'Jester Truck', 1700.00, CAST('2025-12-31' AS DATE), 'On platform');
INSERT INTO VEHICLE (DRIVER_ID, VEHICLE_TYPE, LICENSE_PLATE, MODEL, CAPACITY, INSURANCE_EXPIRY, STATUS) VALUES (9, 1, 'FESTIVE567', 'Party Machine', 1800.00, CAST('2025-12-31' AS DATE), 'Busy');
INSERT INTO VEHICLE (DRIVER_ID, VEHICLE_TYPE, LICENSE_PLATE, MODEL, CAPACITY, INSURANCE_EXPIRY, STATUS) VALUES (10, 2, 'PARTY890', 'Fun Cruiser', 2000.00, CAST('2025-12-31' AS DATE), 'Available');

--Заполнение таблицы VEHICLE_TYPE
INSERT INTO VEHICLE_TYPE (NAME, DESCRIPTION) VALUES ('Party Van', 'A van for all your party needs');
INSERT INTO VEHICLE_TYPE (NAME, DESCRIPTION) VALUES ('Joy Ride', 'A fun vehicle for exciting trips');
INSERT INTO VEHICLE_TYPE (NAME, DESCRIPTION) VALUES ('Giggle Bus', 'A bus that makes you laugh');
INSERT INTO VEHICLE_TYPE (NAME, DESCRIPTION) VALUES ('Bouncy Car', 'A car that brings joy');
INSERT INTO VEHICLE_TYPE (NAME, DESCRIPTION) VALUES ('Happy Truck', 'A truck filled with happiness');
INSERT INTO VEHICLE_TYPE (NAME, DESCRIPTION) VALUES ('Jolly Ride', 'A ride that makes you smile');
INSERT INTO VEHICLE_TYPE (NAME, DESCRIPTION) VALUES ('Fun Express', 'The express for fun deliveries');
INSERT INTO VEHICLE_TYPE (NAME, DESCRIPTION) VALUES ('Smiley Van', 'A van that spreads smiles');
INSERT INTO VEHICLE_TYPE (NAME, DESCRIPTION) VALUES ('Cheerful Cruiser', 'A cruiser that lifts your spirits');
INSERT INTO VEHICLE_TYPE (NAME, DESCRIPTION) VALUES ('Festival Truck', 'A truck perfect for festivals');

--Заполнение таблицы SERVICE_TYPE 
INSERT INTO SERVICE_TYPE (NAME, DESCRIPTION) VALUES ('Fun Delivery', 'Delivery with a smile');
INSERT INTO SERVICE_TYPE (NAME, DESCRIPTION) VALUES ('Joy Ride', 'Exciting rides with fun');
INSERT INTO SERVICE_TYPE (NAME, DESCRIPTION) VALUES ('Party Planning', 'Planning your perfect party');
INSERT INTO SERVICE_TYPE (NAME, DESCRIPTION) VALUES ('Giggle Service', 'Service that brings laughter');
INSERT INTO SERVICE_TYPE (NAME, DESCRIPTION) VALUES ('Celebration Support', 'Supporting your celebrations');
INSERT INTO SERVICE_TYPE (NAME, DESCRIPTION) VALUES ('Happy Transport', 'Transport that makes you happy');
INSERT INTO SERVICE_TYPE (NAME, DESCRIPTION) VALUES ('Cheerful Assistance', 'Assistance with a cheerful touch');
INSERT INTO SERVICE_TYPE (NAME, DESCRIPTION) VALUES ('Jolly Events', 'Events that spread joy');
INSERT INTO SERVICE_TYPE (NAME, DESCRIPTION) VALUES ('Smiley Services', 'Services that put a smile on your face');
INSERT INTO SERVICE_TYPE (NAME, DESCRIPTION) VALUES ('Fun Experiences', 'Experiences that are fun-filled');

--Заполнение таблицы SERVICES
INSERT INTO SERVICES (NAME, DESCRIPTION, BASE_RATE, SERVICE_TYPE_ID, CREATED_AT) VALUES ('Happy Delivery', 'Delivering happiness', 50.00, 1, CURRENT_TIMESTAMP);
INSERT INTO SERVICES (NAME, DESCRIPTION, BASE_RATE, SERVICE_TYPE_ID, CREATED_AT) VALUES ('Joyful Ride', 'An exciting ride for you', 70.00, 2, CURRENT_TIMESTAMP);
INSERT INTO SERVICES (NAME, DESCRIPTION, BASE_RATE, SERVICE_TYPE_ID, CREATED_AT) VALUES ('Party Planner', 'Planning your fun events', 100.00, 3, CURRENT_TIMESTAMP);
INSERT INTO SERVICES (NAME, DESCRIPTION, BASE_RATE, SERVICE_TYPE_ID, CREATED_AT) VALUES ('Giggle Service', 'Service that makes you laugh', 60.00, 4, CURRENT_TIMESTAMP);
INSERT INTO SERVICES (NAME, DESCRIPTION, BASE_RATE, SERVICE_TYPE_ID, CREATED_AT) VALUES ('Celebration Transport', 'Transport for your celebrations', 80.00, 5, CURRENT_TIMESTAMP);
INSERT INTO SERVICES (NAME, DESCRIPTION, BASE_RATE, SERVICE_TYPE_ID, CREATED_AT) VALUES ('Cheerful Delivery', 'Deliveries that spread cheer', 55.00, 6, CURRENT_TIMESTAMP);
INSERT INTO SERVICES (NAME, DESCRIPTION, BASE_RATE, SERVICE_TYPE_ID, CREATED_AT) VALUES ('Fun Events', 'Making your events fun', 90.00, 7, CURRENT_TIMESTAMP);
INSERT INTO SERVICES (NAME, DESCRIPTION, BASE_RATE, SERVICE_TYPE_ID, CREATED_AT) VALUES ('Smiley Service', 'Service that brings smiles', 75.00, 8, CURRENT_TIMESTAMP);
INSERT INTO SERVICES (NAME, DESCRIPTION, BASE_RATE, SERVICE_TYPE_ID, CREATED_AT) VALUES ('Jolly Transport', 'Joyful transport services', 85.00, 9, CURRENT_TIMESTAMP);
INSERT INTO SERVICES (NAME, DESCRIPTION, BASE_RATE, SERVICE_TYPE_ID, CREATED_AT) VALUES ('Fun Experience', 'Creating fun experiences for you', 95.00, 10, CURRENT_TIMESTAMP);

--Заполнение таблицы ROUTES
INSERT INTO ROUTES (START_LOCATION, END_LOCATION, DISTANCE) VALUES ('Joyful Park', 'Happy Avenue', 5.0);
INSERT INTO ROUTES (START_LOCATION, END_LOCATION, DISTANCE) VALUES ('Party Central', 'Giggle Lane', 10.0);
INSERT INTO ROUTES (START_LOCATION, END_LOCATION, DISTANCE) VALUES ('Smiley Beach', 'Fun Island', 15.0);
INSERT INTO ROUTES (START_LOCATION, END_LOCATION, DISTANCE) VALUES ('Laughter City', 'Joy Road', 20.0);
INSERT INTO ROUTES (START_LOCATION, END_LOCATION, DISTANCE) VALUES ('Cheerful Valley', 'Merry Hill', 8.0);
INSERT INTO ROUTES (START_LOCATION, END_LOCATION, DISTANCE) VALUES ('Happy Town', 'Gigglesburg', 12.0);
INSERT INTO ROUTES (START_LOCATION, END_LOCATION, DISTANCE) VALUES ('Fun Village', 'Jolly Farm', 9.0);
INSERT INTO ROUTES (START_LOCATION, END_LOCATION, DISTANCE) VALUES ('Wonderland', 'Fantasy Land', 25.0);
INSERT INTO ROUTES (START_LOCATION, END_LOCATION, DISTANCE) VALUES ('Joyful Gardens', 'Blissful Meadows', 14.0);
INSERT INTO ROUTES (START_LOCATION, END_LOCATION, DISTANCE) VALUES ('Cheerful Heights', 'Happiness Valley', 18.0);