CREATE INDEX IDX_Orders_ClientID ON ORDERS (CLIENT_ID);
CREATE INDEX IDX_Vehicle_DriverID ON VEHICLE (DRIVER_ID);

SELECT INDEX_NAME, TABLE_NAME FROM USER_INDEXES WHERE TABLE_NAME = 'ORDERS';
SELECT INDEX_NAME, TABLE_NAME FROM USER_INDEXES WHERE TABLE_NAME = 'VEHICLE';