SELECT * FROM CLIENT;
SELECT * FROM CLIENT_INFO;
SELECT * FROM DRIVER;
SELECT * FROM DRIVER_INFO;
SELECT * FROM CARGO;
SELECT * FROM CARGO_TYPE;
SELECT * FROM ORDERS;
SELECT * FROM VEHICLE;
SELECT * FROM VEHICLE_TYPE;
SELECT * FROM SERVICE_TYPE;
SELECT * FROM SERVICES; 
SELECT * FROM ROUTES;

-- Информации о клиентах
CREATE TABLE CLIENT (
	ID number(4) generated by default on null as identity,
	LOGIN
	PASSWORD
);

-- Дополнительная информация о клиентах
CREATE TABLE CLIENT_INFO (
	ID number(4) generated by default on null as identity,
	CLIENT_ID
	FIRST_NAME
	LAST_NAME
	MIDDLE_NAME
	ADDRESS
	EMAIL
	PHONE_NUMBER
);

-- Информация о водителях
CREATE TABLE DRIVER (
	ID number(4) generated by default on null as identity,
	DRIVER_ID
	LOGIN
	PASSWORD
);

-- Дополнительная информация о водителях
CREATE TABLE DRIVER_INFO (
	ID number(4) generated by default on null as identity,
	DRIVER_ID
	FIRST_NAME
	LAST_NAME
	MIDDLE_NAME
	ADDRESS
	BIRTH_DATE
	EMAIL
	PASSPORT_NUM
	PHONE_NUMBER
	VEHICLE_INFO
	
);

-- Информация о грузах
CREATE TABLE CARGO (
	ID number(4) generated by default on null as identity,
	CARGO_ID
	NAME
	DESCRIPTION
	WEIGHT
	VOLUME
	CARGO_TYPE
	HAZARDOUS
);

-- Типы грузов
CREATE TABLE CARGO_TYPE (
	ID number(4) generated by default on null as identity,
	NAME
	DESCRIPTION
	
);

-- Информация о заказах
CREATE TABLE ORDERS (
    ID number(4) generated by default on null as identity,
    CLIENT_ID
    SERVICE_ID
    STATUS
    CREATED_AT
    ROUTE
    DELIVERY_TYPE
    TOTAL_WEIGHT
    TOTAL_VOLUME
);

-- Информация о транспортных средствах
CREATE TABLE VEHICLE (
	ID number(4) generated by default on null as identity,
	DRIVER_ID
	VEHICLE_TYPE
	LICENSE_PLATE
	MODEL
	CAPACITY
	INSURANCE_EXPIRY
	STATUS
);

-- Типы транспортных средств
CREATE TABLE VEHICLE_TYPE (
	ID number(4) generated by default on null as identity,
	NAME
	DESCRIPTION
);

-- Типы услуг
CREATE TABLE SERVICE_TYPE (
	ID number(4) generated by default on null as identity,
	NAME
	DESCRIPTION
);

-- Информация об услугах
CREATE TABLE SERVICES (
	ID number(4) generated by default on null as identity,
	NAME
	DESCRIPTION
	BASE_RATE
	SERVICE_TYPE
	CREATED_AT
);

-- Информация о маршрутах
CREATE TABLE ROUTES (
	ID number(4) generated by default on null as identity,
	START_LOCATION
	END_LOCATION
	DISTANCE
);



--- во второй лабе надо еще сделать функции (5 функций), процедуры (5 разных (не только круды)) -- 10 должно быть вообщем, последовательности, триггеры (1), индексы (2), их вызовы и т.д.
--- по листам задания: 
