SELECT * FROM CLIENT;
SELECT * FROM CLIENT_INFO;
SELECT * FROM DRIVER;
SELECT * FROM DRIVER_INFO; 
SELECT * FROM CARGO; 
SELECT * FROM CARGO_TYPE;
SELECT * FROM ORDERS; 
SELECT * FROM VEHICLE;  
SELECT * FROM VEHICLE_TYPE;
SELECT * FROM SERVICE_TYPE;
SELECT * FROM SERVICES; 
SELECT * FROM ROUTES;

-- Информация о клиентах
CREATE TABLE CLIENT (
    ID SERIAL PRIMARY KEY,
    LOGIN VARCHAR(255) NOT NULL, 
    PASSWORD VARCHAR(255) NOT NULL
);

-- Дополнительная информация о клиентах
CREATE TABLE CLIENT_INFO (
    ID SERIAL PRIMARY KEY,
    CLIENT_ID INT NOT NULL,
    FIRST_NAME VARCHAR(50) NOT NULL, 
    LAST_NAME VARCHAR(50) NOT NULL, 
    MIDDLE_NAME VARCHAR(50) NOT NULL, 
    ADDRESS VARCHAR(255), 
    EMAIL VARCHAR(100),
    PHONE_NUMBER VARCHAR(50), 
    FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT(ID)
);

-- Информация о водителях
CREATE TABLE DRIVER (
    ID SERIAL PRIMARY KEY,
    LOGIN VARCHAR(255) NOT NULL, 
    PASSWORD VARCHAR(255) NOT NULL
);

-- Дополнительная информация о водителях 
CREATE TABLE DRIVER_INFO (
    ID SERIAL PRIMARY KEY,
    DRIVER_ID INT NOT NULL,
    FIRST_NAME VARCHAR(50) NOT NULL, 
    LAST_NAME VARCHAR(50) NOT NULL, 
    MIDDLE_NAME VARCHAR(50) NOT NULL, 
    ADDRESS VARCHAR(255), 
    BIRTH_DATE DATE,
    EMAIL VARCHAR(100),
    PASSPORT_NUM VARCHAR(50) NOT NULL, 
    PHONE_NUMBER VARCHAR(50), 
    VEHICLE_INFO INT NOT NULL,  
    FOREIGN KEY (DRIVER_ID) REFERENCES DRIVER(ID),
    FOREIGN KEY (VEHICLE_INFO) REFERENCES VEHICLE(ID)
);

-- Информация о грузах 
CREATE TABLE CARGO ( 
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL, 
    DESCRIPTION VARCHAR(255),
    WEIGHT DECIMAL(10, 2) NOT NULL, 
    VOLUME DECIMAL(10, 2) NOT NULL, 
    CARGO_TYPE INT,  
    HAZARDOUS VARCHAR(7) CHECK (HAZARDOUS IN ('No', 'Class 1', 'Class 2', 'Class 3', 'Class 4', 'Class 5', 'Class 6', 'Class 7', 'Class 8', 'Class 9')),
    FOREIGN KEY (CARGO_TYPE) REFERENCES CARGO_TYPE(ID)
);

-- Типы грузов
CREATE TABLE CARGO_TYPE (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL, 
    DESCRIPTION VARCHAR(255) NOT NULL
);

-- Информация о заказах 
CREATE TABLE ORDERS (
    ID SERIAL PRIMARY KEY,
    CLIENT_ID INT NOT NULL,
    DRIVER_ID INT, 
    SERVICE_ID INT NOT NULL,
    STATUS VARCHAR(50) CHECK (STATUS IN ('Pending', 'In Transit', 'Delivered', 'Cancellation Requested', 'Cancelled', 'On Hold', 'Returned', 'Lost', 'Awaiting Pickup', 'Out for Delivery', 'Completed', 'Exception', 'Scheduled', 'In Warehouse', 'Awaiting Clearance', 'Delayed')),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ROUTE INT NOT NULL,
    DELIVERY_TYPE VARCHAR(50) NOT NULL,
    TOTAL_WEIGHT DECIMAL(10, 2),
    TOTAL_VOLUME DECIMAL(10, 2),
    DELIVERED_AT TIMESTAMP,
    FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT(ID),
    FOREIGN KEY (DRIVER_ID) REFERENCES DRIVER(ID),  
    FOREIGN KEY (SERVICE_ID) REFERENCES SERVICES(ID),
    FOREIGN KEY (ROUTE) REFERENCES ROUTES(ID)
);

-- Информация о транспортных средствах 
CREATE TABLE VEHICLE ( 
    ID SERIAL PRIMARY KEY,
    DRIVER_ID INT NOT NULL,
    VEHICLE_TYPE INT NOT NULL,  
    LICENSE_PLATE VARCHAR(20) NOT NULL,
    MODEL VARCHAR(50) NOT NULL, 
    CAPACITY DECIMAL(10, 2) NOT NULL, 
    INSURANCE_EXPIRY DATE NOT NULL,
    STATUS VARCHAR(20) CHECK (STATUS IN ('In transit', 'Arrived', 'At stop', 'Delayed', 'Cancelled', 'Under maintenance', 'Available', 'On route', 'Delivered', 'Waiting', 'Issue with cargo', 'Free', 'Busy', 'Searching', 'Completed', 'On platform')),  
    FOREIGN KEY (DRIVER_ID) REFERENCES DRIVER(ID),
    FOREIGN KEY (VEHICLE_TYPE) REFERENCES VEHICLE_TYPE(ID)  
);

-- Типы транспортных средств
CREATE TABLE VEHICLE_TYPE (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL
);

-- Типы услуг
CREATE TABLE SERVICE_TYPE (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL
);

-- Информация об услугах
CREATE TABLE SERVICES (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    BASE_RATE DECIMAL(10, 2),  
    SERVICE_TYPE_ID INT,  
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (SERVICE_TYPE_ID) REFERENCES SERVICE_TYPE(ID)
);

-- Информация о маршрутах
CREATE TABLE ROUTES (
    ID SERIAL PRIMARY KEY,
    START_LOCATION VARCHAR(255) NOT NULL,  
    END_LOCATION VARCHAR(255) NOT NULL,    
    DISTANCE DECIMAL(10, 2)            
);