CREATE FUNCTION dbo.GetOrdersByDateRange
(
    @StartDate DATETIME,
    @EndDate DATETIME
)
RETURNS TABLE
AS
RETURN
(
    SELECT 
        o.ID AS OrderID,
        c.LOGIN AS ClientLogin,
        cinfo.FIRST_NAME AS ClientFirstName,
        cinfo.LAST_NAME AS ClientLastName,
        d.LOGIN AS DriverLogin,
        dinfo.FIRST_NAME AS DriverFirstName,
        dinfo.LAST_NAME AS DriverLastName,
        o.CREATED_AT,
        o.DELIVERED_AT,
        o.STATUS,
        o.TOTAL_WEIGHT,
        o.TOTAL_VOLUME
    FROM 
        ORDERS o
    JOIN 
        CLIENT c ON o.CLIENT_ID = c.ID
    JOIN 
        CLIENT_INFO cinfo ON cinfo.CLIENT_ID = c.ID
    LEFT JOIN 
        DRIVER d ON o.DRIVER_ID = d.ID
    LEFT JOIN 
        DRIVER_INFO dinfo ON dinfo.DRIVER_ID = d.ID
    WHERE 
        o.CREATED_AT BETWEEN @StartDate AND @EndDate
);

SELECT * FROM dbo.GetOrdersByDateRange('2025-04-13', '2025-04-16');
select * from ORDERS;
delete from ORDERS;




ALTER TABLE ORDERS
ALTER COLUMN CLIENT_ID INT NULL;

ALTER TABLE ORDERS
ALTER COLUMN DRIVER_ID INT NULL;

ALTER TABLE ORDERS
ALTER COLUMN SERVICE_ID INT NULL;

ALTER TABLE ORDERS
ALTER COLUMN STATUS NVARCHAR(100) NULL;

ALTER TABLE ORDERS
ALTER COLUMN CREATED_AT DATETIME NULL;

ALTER TABLE ORDERS
ALTER COLUMN ROUTE INT NULL;

ALTER TABLE ORDERS
ALTER COLUMN DELIVERY_TYPE NVARCHAR(100) NULL;

ALTER TABLE ORDERS
ALTER COLUMN TOTAL_WEIGHT INT NULL;

ALTER TABLE ORDERS
ALTER COLUMN TOTAL_VOLUME INT NULL;

ALTER TABLE ORDERS
ALTER COLUMN DELIVERED_AT DATETIME NULL;

delete from orders;
select * from orders;