### 
@hp=http://localhost:5041
@capi=/api/cel
### для теста на VSCode установить расширение REST Client


###  все знаменитости
###  celebrities.MapGet("/", 
GET {{hp}}{{capi}} 

### знаменитость по ID
### MapGet("/{id:int:min(1)}"
GET {{hp}}{{capi}}/7

### знаменитость по ID события 
### MapGet("/le/{id:int:min(1)}"
GET {{hp}}{{capi}}/le/7

###  удалить знаменитость по ID
###.MapDelete("/{id:int:min(1)}",
DELETE {{hp}}{{capi}}/4


###  добавить новую знаменитость
###  MapPost("/",
POST {{hp}}{{capi}}
Content-Type:application/json

  {
    "fullName":    "Ershov Andrey",
    "nationality": "RU",
    "reqPhotoPath":"Ershov.jpg"
  }

###  обновить знаменитость по ID  
###  MapPut("/{id:int:min(1)}", 
PUT {{hp}}{{capi}}/13
Content-Type:application/json

 {
    "fullName":    "Tim Berners",
    "nationality": "RU",
    "reqPhotoPath":"Ershov.jpg"
  }


### получить файл фотографии по имени файла (fname)
### MapGet("/photo/{fname}"
GET {{hp}}{{capi}}/photo/Knuth.jpg


### 
@lapi=/api/le
###

###  все события
###  MapGet("/",
GET {{hp}}{{lapi}}



###  событие по ID
###  MapGet("/{id:int:min(1)}"
GET {{hp}}{{lapi}}/10


###  все события по ID знаменитости
###  MapGet("/cel/{id:int:min(1)}
GET {{hp}}{{lapi}}/cel/3


###  удаление события по ID
###  MapDelete("/{id:int:min(1)}"
DELETE {{hp}}{{lapi}}/10



###  добавление нового события
###  MapPost("/", 
POST {{hp}}{{lapi}}
Content-Type:application/json

{
    "celebrityId": 13,
    "date": "1931-04-19T00:00:00",
    "description": "Дата перерождения",
    "reqPhotoPath": null
 }

###  обновить событие по ID 
###  MapPut("/{id:int:min(1)}"
PUT {{hp}}{{lapi}}/2
Content-Type:application/json

{
    "celebrityId": 13,
    "date": "1931-04-19T00:00:00",
    "description": "Hello World.",
    "reqPhotoPath": null
}


###